---
title: "5. Modelos de Cox"
format: html
---

# 4. Modelos de Cox:

Creación de la base de datos:

```{r, include=F}
load("1. Bases de datos/1. Originales/mortality19_predimed.Rdata")
load("1. Bases de datos/1. Originales/vars_necesarias_updated.Rdata")
scores = read_excel("2. Resultados/2. datos/20250113_Scores.xlsx")
FFQ = read_sav("1. Bases de datos/1. Originales/FFQ_PREDIMED_2012.SAV")
FFQ=data.frame(cbind(id=FFQ$id,energiat = FFQ$energiat,alcoholg = FFQ$alcoholg)) 
BBDDmet = merge(BBDDmet, mortality19_predimed, by = 'id')
BBDDmet = merge(BBDDmet, scores, by = 'id')
BBDDmet = merge(BBDDmet, sub_base, by = 'id')
BBDDmet = merge(BBDDmet, FFQ, by = 'id')
```

```{r}
#colnames(BBDDmet)
BBDDmet$date = as.POSIXct(BBDDmet$datinclu, format="%m/%d/%Y")
str(BBDDmet$datinclu)
str(BBDDmet$date)
str(BBDDmet$date_censored19)
BBDDmet$follcox_19 = as.numeric(difftime(BBDDmet$date_censored19, BBDDmet$date, units = "days"))/365.25

BBDDmet$diab_sd = as.numeric(ifelse(BBDDmet$diab_est >= 1, "1", "0"))
BBDDmet$homa_sd = BBDDmet$homa_est/sd(BBDDmet$homa_est)
```

```{r}
approaches = c("diab_est",
                "homa_est",
                "diab_sd",
                "homa_sd")

reales = c("cens.x",
            "homa0_0.x",
            "cens.x",
            "homa0_0.x")

formu_model1 = list()
fit_model1 = list()
formu_model2 = list()
fit_model2 = list()
formu_model3 = list()
fit_model3 = list()
formu_model4 = list()
fit_model4 = list()

for (i in 1:4){
  
  formu_model1[[i]] = as.formula(paste0("Surv(follcox_19, death19) ~ ", approaches[i], 
                                         "* cut2(edad0,g=2) + strata(sexo) + ps1 + ps2 + strata(as.factor(grup_int)) +
                                         strata(as.factor(nodo))"))
  fit_model1[[i]] = coxph(formu_model1[[i]], weights=w, data = BBDDmet)
  
  formu_model2[[i]] = as.formula(paste0("Surv(follcox_19, death19) ~ ", approaches[i], 
                                         "* cut2(edad0,g=2) + strata(sexo) + ps1 + ps2 + strata(as.factor(grup_int)) +
                                         strata(as.factor(nodo)) + cut2(imc1, g = 2) + as.factor(fum) + 
                                         educat + getota_1.x + as.factor(hipercol0.x) + as.factor(hta0.x) + as.factor(tra_col0.x) + as.factor(trathta0.x)"))
  fit_model2[[i]] = coxph(formu_model2[[i]], weights=w, data = BBDDmet)
  
  formu_model3[[i]] = as.formula(paste0("Surv(follcox_19, death19) ~ ", approaches[i], 
                                         "* cut2(edad0, g = 2) + strata(sexo) +  as.factor(fum) + ps1 + ps2 + 
                                         strata(as.factor(grup_int)) +
                                         strata(as.factor(nodo)) + cut2(imc1, g = 2) + energiat + alcoholg +   
                                         educat + getota_1.x + as.factor(hipercol0.x) + as.factor(hta0.x) + as.factor(tra_col0.x) + 
                                         as.factor(trathta0.x) + p14"))
  fit_model3[[i]] = coxph(formu_model3[[i]], weights=w, data = BBDDmet)

  formu_model4[[i]] = as.formula(paste0("Surv(follcox_19, death19) ~ ", approaches[i], 
                                         "* cut2(edad0, g = 2) + strata(sexo) +  as.factor(fum) + ps1 + ps2 + 
                                         strata(as.factor(grup_int)) + energiat + alcoholg +
                                         strata(as.factor(nodo)) + cut2(imc1, g = 2) +   
                                         educat + getota_1.x + as.factor(hipercol0.x) + as.factor(hta0.x) + as.factor(tra_col0.x) + 
                                         as.factor(trathta0.x) + p14 +", reales[i]))
  fit_model4[[i]] = coxph(formu_model4[[i]], weights=w, data = BBDDmet)
}

results_model1 = matrix(NA, 4, 4)
results_model2 = matrix(NA, 4, 4)
results_model3 = matrix(NA, 4, 4)
results_model4 = matrix(NA, 4, 4)

rownames(results_model1) = c("diab_est",
                              "homa_est",
                              "diab_sd",
                              "homa_sd")

rownames(results_model2)=rownames(results_model1)
rownames(results_model3)=rownames(results_model1)
rownames(results_model4)=rownames(results_model1)

colnames(results_model1)=c("HR", "lower 95% CI", "upper 95% CI", "P_value")
colnames(results_model2)=colnames(results_model1)
colnames(results_model3)=colnames(results_model1)
colnames(results_model4)=colnames(results_model1)

for (i in 1:4){
  get_data_sum = summary(fit_model1[[i]])
  hr_data = get_data_sum$conf.int[1,c("exp(coef)", "lower .95", "upper .95")]
  
  results_model1[i,1] = round(hr_data[1], 3)
  results_model1[i,2] = round(hr_data[2], 3)
  results_model1[i,3] = round(hr_data[3], 3)
  results_model1[i,4] = round(get_data_sum$coefficients[1,6], 3)  # Pvalue
  
  get_data_sum = summary(fit_model2[[i]])
  hr_data = get_data_sum$conf.int[1,c("exp(coef)", "lower .95", "upper .95")]
  
  results_model2[i,1] = round(hr_data[1], 3)
  results_model2[i,2] = round(hr_data[2], 3)
  results_model2[i,3] = round(hr_data[3], 3)
  results_model2[i,4] = round(get_data_sum$coefficients[1,6], 3)  # Pvalue
  
  get_data_sum = summary(fit_model3[[i]])
  hr_data = get_data_sum$conf.int[1,c("exp(coef)", "lower .95", "upper .95")]
  
  results_model3[i,1] = round(hr_data[1], 3)
  results_model3[i,2] = round(hr_data[2], 3)
  results_model3[i,3] = round(hr_data[3], 3)
  results_model3[i,4] = round(get_data_sum$coefficients[1,6], 3)  # Pvalue
  
  get_data_sum = summary(fit_model4[[i]])
  hr_data = get_data_sum$conf.int[1,c("exp(coef)", "lower .95", "upper .95")]
  
  results_model4[i,1] = round(hr_data[1], 3)
  results_model4[i,2] = round(hr_data[2], 3)
  results_model4[i,3] = round(hr_data[3], 3)
  results_model4[i,4] = round(get_data_sum$coefficients[1,6], 3)  # Pvalue
}

full_results = rbind(c("Model 1"),results_model1, 
                      c("Model 2"),results_model2,
                      c("Model 3"),results_model3,
                      c("Model 4"),results_model4)

modelos = data.frame(full_results)
modelos$names = rownames(modelos)
```

```{r}
export(modelos, "E:/Trabajo/1. UNH/Articulos/1. En Preparación/1. Articulos/1. Autor/PREDIMED/ART Metabolitos Diab - Mortalidad/2. Análisis estadístico/20250129_modelos_T2D_basal.xlsx")
#export(BBDDmet, "E:/Trabajo/1. UNH/Articulos/1. En Preparación/1. Articulos/1. Autor/PREDIMED/ART Metabolitos Diab - Mortalidad/2. Análisis estadístico/BBDDmet_20250129.csv")

rm(approaches, fit_model1, fit_model2, fit_model3, fit_model4, reales, formu_model1, formu_model2, formu_model3,
   formu_model4, full_results, get_data_sum, hr_data, modelos, results_model1, results_model2, results_model3,
   results_model4, i)
```


# 4.1. Petición del revisor: eGFR y variables de mortalidad:

```{r}
PREDIMED_old =
    read_sav("1. Bases de datos/1. Originales/BD_ExtendedFU_Alim_Lab_renal-03.12.15-LACTIS-CCR.sav")
```

```{r}
review1 = BBDDmet %>%
  left_join(PREDIMED_old %>%
              select(id, CKD_EPI_v0),
            by = "id") %>%
  filter(CKD_EPI_v0 > 0) %>%
  mutate(diab_est_q = if_else(is.na(diab_est),
                              NA_integer_,
                              ntile(diab_est, 4)) %>% 
           factor(levels = 1:4),
         homa_sd_q = if_else(is.na(homa_sd),
                             NA_integer_,
                             ntile(homa_sd, 4)
                             ) %>% 
           factor(levels = 1:4))
```

```{r}
review1 %>%
  filter(CKD_EPI_v0 > 0) %>%
  count(death19)
```


```{r}
models = list(
  "Model 1" = list(covariates = "* cut2(edad0,g=2) + strata(sexo) + ps1 + ps2 + 
                                  strata(as.factor(grup_int)) +
                                  strata(as.factor(nodo))"),
  "Model 2" = list(covariates = "* cut2(edad0,g=2) + strata(sexo) + ps1 + ps2 + strata(as.factor(grup_int)) +
                                  strata(as.factor(nodo)) + cut2(imc1, g = 2) + as.factor(fum) + 
                                  educat + getota_1.x + as.factor(hipercol0.x) + as.factor(hta0.x) +
                                  as.factor(tra_col0.x) + as.factor(trathta0.x)"),
  "Model 3" = list(covariates = "* cut2(edad0, g = 2) + strata(sexo) +  as.factor(fum) + ps1 + ps2 +
                                  strata(as.factor(grup_int)) +
                                  strata(as.factor(nodo)) + cut2(imc1, g = 2) + energiat + alcoholg +   
                                  educat + getota_1.x + as.factor(hipercol0.x) + as.factor(hta0.x) +
                                  as.factor(tra_col0.x) + as.factor(trathta0.x) + p14 + CKD_EPI_v0"))

approaches = c("diab_est", "homa_sd",
               "diab_est_q", "homa_sd_q",
               "as.numeric(diab_est_q)", "as.numeric(homa_sd_q)")

run_cox_models(data = review1,
               approaches = approaches,
               models = models,
               time_var = "follcox_19",
               event_var = "death19", robust = T, weights = "w",
               export_path = "2. Resultados/3. modelos/20260202_modelos_mortalidad_egfr_review.xlsx")
```