---
title: "7. Figuras"
format: html
---

# 6. Figuras:

## 6.1. Diagrama de Venn:

```{r}
DT2 = read_excel("2. Resultados/2. datos/Only coef_binomial_diabetes.xlsx")
HOMA = read_excel("2. Resultados/2. datos/Only coef_gaussian_HOMA.xlsx")

set_DT2 = (DT2$Metabolites)
set_HOMA = (HOMA$Metabolites)

venn.diagram(x = list(set_DT2,set_HOMA),
             filename = 'venn_tot.png',
             output = T, 
             
             # Output features
             imagetype="png" , 
             resolution = 300,
             
             # Circles
             lwd = 7,
             # Numbers
             cex = 1.5,
             fontface = "bold",
             fontfamily = "sans",
             
             # Set names
             cat.cex = 2,
             category.names = c("T2D", "HOMA"),
             cat.default.pos = "text",
             cat.fontface = "bold",
             cat.fontfamily = "sans",
             cat.pos = 2)

set_DT2 = subset(DT2$Metabolites, DT2$mean >= 0)
set_HOMA = subset(HOMA$Metabolites, HOMA$mean >= 0)

venn.diagram(x = list(set_DT2,set_HOMA),
             filename = 'venn_pos.png',
             output = T, 
             
             # Output features
             imagetype="png" , 
             resolution = 300,
             
             # Circles
             lwd = 7,
             # Numbers
             cex = 1.5,
             fontface = "bold",
             fontfamily = "sans",
             
             # Set names
             cat.cex = 2,
             category.names = c("T2D", "HOMA"),
             cat.default.pos = "text",
             cat.fontface = "bold",
             cat.fontfamily = "sans",
             cat.pos = 2)

set_DT2 = subset(DT2$Metabolites, DT2$mean <0)
set_HOMA = subset(HOMA$Metabolites, HOMA$mean <0)

venn.diagram(x = list(set_DT2,set_HOMA),
             filename = 'venn_neg.png',
             output = T, 
             
             # Output features
             imagetype="png" , 
             resolution = 300,
             
             # Circles
             lwd = 7,
             # Numbers
             cex = 1.5,
             fontface = "bold",
             fontfamily = "sans",
             
             # Set names
             cat.cex = 2,
             category.names = c("T2D", "HOMA"),
             cat.default.pos = "text",
             cat.fontface = "bold",
             cat.fontfamily = "sans",
             cat.pos = 2)
```

## 6.2. Correlaciones entre los metabolitos comunes:

```{r, include=F}
df = merge(DT2, HOMA, by = "Metabolites")

met2 = BBDDmet[,(names(BBDDmet) %in% df$Metabolites)]
met2 = cbind(met2, diab_est = BBDDmet$diab_est,
             HOMA_est = BBDDmet$homa_est, HOMA = BBDDmet$homa0_0.y,
             Insulina = BBDDmet$insulin0_0, Glucosa = BBDDmet$glucose0_0)

mat = cor(met2, use = "complete.obs")
mat1 = cor.mtest(met2, conf.level = 0.95)
```

```{r}
png(filename = "Supplemental Figure 1.png", width = 30, height = 30, res=300, unit="cm")
corrplot(mat, method = 'color', type = "upper", addCoef.col = "black", diag = F, col = COL2('RdBu', 10), p.mat = mat1$p, sig.level = 0.05)
dev.off()
```

```{r}
rm(df, mat, mat1, met2, set_DT2, set_HOMA)
```
